name: Trigger on Pull Request Approval

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  print-commit-sha:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print commit SHA
        run: |
          echo "Commit SHA: ${{ github.event.pull_request.head.sha }}"
